### PR TITLE
LICENSE should have license info for third-party libraries

### PR DESCRIPTION
**Pull request by mrerrormessage**

### CODE REVIEW

**Comment by TheBizzle** [comment]
We don't need license info for stuff that's just used internally or by the build system or for testing.  It's about libraries that run parts of the compiler or engine.

**Comment by mrerrormessage** [comment]
So it sounds like we just need:
* Lodash
* Mori
* Json4s
* Scalaz
Do we need to include license information for coffeescript or scala/scala standard library?

**Comment by TheBizzle** [comment]
> Do we need to include license information for coffeescript or scala/scala standard library?

No

**Comment by mrerrormessage** [comment]
Sounds good. Should be ready for review.

**Pull request closed without merging**
