### PR TITLE
Addressed issues raised by Jeremy B.

### PR DESCRIPTION
**Pull request by CIVITAS-John**
Hi there,

I hope this commit could address your issues, as I manually tested those new primitives.

Thanks!

### CODE REVIEW

**Review by LaCuneta — CHANGES_REQUESTED** [review]
Hey John, thanks for the improvements!  This is looking good, almost there.

Just to let you know, you don't have to close and re-open a pull request when you have changes.  If you just add commits to your branch in your repository, they should then be shown in the PR as well.  Then I can re-review the new changes.  That's the expected GitHub workflow since it keeps the whole "start to finish" evolution and discussion of the changes in one place.

With the changes to fix the prior issue with arrays, it doesn't seem to me that the `typeof(value) is 'object'` checks are necessary in the `jsonObjectToTable()` method [here for arrays](https://github.com/NetLogo/Tortoise/blob/b7076b0f1e30a948a7a010c68d196dbfb14ecba2/engine/src/main/coffee/extensions/table.coffee#L90-L93) and [here for objects](https://github.com/NetLogo/Tortoise/blob/b7076b0f1e30a948a7a010c68d196dbfb14ecba2/engine/src/main/coffee/extensions/table.coffee#L99-L100).  Because the method itself does the checks, you can just recursively call it and if the value is not an object it'll fall through to [the unmodified return value](https://github.com/NetLogo/Tortoise/blob/b7076b0f1e30a948a7a010c68d196dbfb14ecba2/engine/src/main/coffee/extensions/table.coffee#L106).  That'll better mirror how the `tableToJsonObject()` method works as well.

And since I'm asking for changes, I'd also like to see some negative tests for failure scenarios.  Something checking that `table:from-json "[10, 20, 30]"` and maybe `table:to-json patch 0 0` both generate appropriate errors.  It'd also be nice to see a test that empty tables and nested tables both work: `table:from-json "{'boots': {\"size\": 10, \"color\": \"red\", \"arr\": [10, 20, 30]},\"slippers\": {}}"`

**Comment by CIVITAS-John** [comment]
At this moment, I think [10, 20, 30] will return a list - which is probably non-canonical, but some users might indeed need it.

For other requested changes, I agree.

**Comment by CIVITAS-John** [comment]
Hi Jeremy,

Could you check out this version of pull request and see if it matches your expectation?

John

**Comment by LaCuneta** [comment]
@CIVITAS-John The code changes all look good, but I did want to see a couple negative error conditions added to the language tests for invalid input.  If you want to omit the array/list example for now, that's fine, but at least one example of the failure going `to-json` and `from-json`.

**Comment by CIVITAS-John** [comment]
Hi Jeremy,

I might need your help to correctly format the two remaining issues.

It seems that the JSON parser one is a bit hard, since the error string could be different based on different environments? Or should we catch underlying errors and throw it?

**Review by LaCuneta — APPROVED** [review]
Okay, I went ahead and fixed those up.  The first one was just a simple type, it was doing `O> set glob1 table:to-json 0` without checking the error, then trying to check the error on the next line.  

For the other, you are correct we should catch and re-throw the JSON parse error as an extension exception, so that it's clear that's a "normal" error and not something truly odd.  For the message, I hard-coded it to use the current output we get from GraalJS as that is the source of truth for the language tests, but obviously if the message is different in browsers or in desktop that's fine.

**Pull request merged**
