### PR TITLE
Travis builds are often killed before completion

### PR DESCRIPTION
**Pull request by mrerrormessage**
For some weeks now, builds have often been failing to complete on Travis.  For a while, I thought it was due to timing out, but I no longer think that that's the issue.  Travis builds actually say `No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself` when they fail from timeout, and that's not the message that we're getting in this case.  Instead, we get `./sbt: line 54:  3123 Killed                  "$JAVA" $XSS $XMX $XX $ENCODING $JAVA_OPTS $HEADLESS -classpath $SBT_LAUNCH $BOOT "$@"`.

Furthermore, the builds usually end at different points, and after different total lengths of time.  [This one](https://travis-ci.org/NetLogo/Tortoise/builds/57982023) ran for 21 minutes and ended about halfway through the model tests.  [This one](https://travis-ci.org/NetLogo/Tortoise/builds/58021592) ran for just 9 seconds longer, and completed 8 more models.  [This one](https://travis-ci.org/NetLogo/Tortoise/builds/58818395) ran for 30 minutes and hardly touched the model tests.  [This one](https://travis-ci.org/NetLogo/Tortoise/builds/59260838) ran for 43 minutes and got about one-third of the way through the model tests.

I tried using `travis_wait`, and [it changed nothing](https://travis-ci.org/NetLogo/Tortoise/builds/59260838).  I tried forcing the build to print out some text every five minutes, and [it changed nothing](https://travis-ci.org/NetLogo/Tortoise/builds/59272594).  I tried merging the `fix-travis` branch today, and even [that one](https://travis-ci.org/NetLogo/Tortoise/builds/59488314) failed.

I now suspect that this is a memory issue.  Travis [claims](http://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error) to have a 3GB memory limit on their machines.  The SBT process that I have running for Tortoise right now on my local machine is currently at 3.4GB.

This is a pretty significant issue, in my eyes.  Having Travis checking our commits and pull requests is a major boon (when it works).  It would be good to get it back to normal as soon as reasonably possible.

### CODE REVIEW

**Comment by SethTisue** [comment]
which part of this is hypothesized to actually fix the problem?

**Comment by mrerrormessage** [comment]
In terms of the issue, I *believe* that it may be due to the JVM client/server split. I've added the flag `-client` to the build, which seems to make it run more reliably on Travis. By default, the jvm figures out whether it is running in a "server-class" or "client-class" machine at startup, and optimizes itself accordingly. When running in `-server` mode on a virtual machine configured similarly to travis, I was able to generate several JVM hard-crashes when there just wasn't enough memory left to give. I suspect this is due to the fact that the JVM will attempt to compile/optimize much more aggressively in server mode than in client mode, which (presumably) uses more CPU/Memory. The JVM also optimizes GC differently depending on whether one is in client or server mode. This would also *could* explain the memory discrepancies between machines (why Jason's uses 3.4 GB for instance, while Robert's doesn't). There is a lot of conflicting information about `-client` vs `-server`, [this StackOverflow thread](http://stackoverflow.com/questions/198577/real-differences-between-java-server-and-java-client) links to a lot of good resources.

**Comment by mrerrormessage** [comment]
I'm pretty sure at this point that our build is running afoul of the dreaded "OOM Killer". See [this build](https://travis-ci.org/NetLogo/Tortoise/builds/60277808#L4281) with a dmesg dump at the end. We're also seeing errors on builds set with a heap size set 512M smaller because they go more than 10 minutes without output. We can try to mitigate this to a certain extent, but it seems like we're at a really bad spot when we have to carefully balance our memory consumption vs. dead I/O time. I'm wondering whether we could identify some of the slower model tests and remove them from the build, or whether running the language tests as a build step and them the model tests as a separate build step would give us any improvement. Other ideas are welcome.

**Comment by mrerrormessage** [comment]
This branch seems to be passing regularly. I'm rerunning the tests several times to ensure that it's alright. A quick summary of changes and their impact:

### Split out tests differently
The test suites are now as follows
* `fast` - The same as it was before
* `language` - Just TestCommands and TestReporters
* `crawl` - everything that used to be in slow except for test commands and reporters. (I can rename this to slow if desired, but I wanted to leave fast/medium/slow around just in case people liked running them locally).
There seemed to be some kind of contention between TestModels and certain tests within TestCommands that was really problematic for the build. This seems to reduce its impact.

### Rework the relationship between `.travis.yml` and `nightly.sh`
Travis now runs each step of the build through issuing commands to nightly.sh. This allows us to have more precise control over `travis_wait`. We're now using `travis_wait` on the `crawl` portion of the build, but nowhere else.

### JVM Tuning
The parameters in `./sbt` seem to work pretty well on Travis. I'll list out and explain the major ones:
* `+XMX=-Xmx1560M` and `-Xms1560M` - limit the stack, but don't grow it dynamically.
* `-client` - java attempts to detect whether it should run in client or server mode. Server mode gobbles memory on recompilation, client mode less so.
* `-Xverify:none` - We aren't dynamically loading anything, so we don't need verification.
* `-XX:MaxMetaspaceSize=512M` - This seems to allow enough space for Nashorn to compile and run quickly without causing the JVM to exceed memory bounds. Lower values may work, but they may cause the build to run too slowly.

### build.sbt configuration changes
We are now limiting sbt to running two tasks in parallel when testing. This ensures that our memory doesn't get gobbled up unnecessarily by having multiple scalatests running at one time. LogBuffered is always set to false, since there didn't seem to be a reason not to, but this could be changed back as long as it was overridden in `nightly.sh`.

### Test Tagging
Tests are now tagged/filtered with scalatest. This change was initially made to support attempting to run the tests via scalatest directly instead of via sbt (which ended up not working out). Having done the work, however, there seemed no reason to change back, as it made our build somewhat simpler.

**Comment by SethTisue** [comment]
fwiw, in my `.travis.yml` in my Project Euler repo I had to do this to reduce memory usage:

      - ./sbt 'set parallelExecution in Test := false' test

if you decide to reduce the parallelism from 2 to 1, this is the easiest way to do it, and note that it can be done at the place you invoke sbt, without needing to modify build.sbt. fwiw.

**Comment by mrerrormessage** [comment]
That makes sense. I believe I played around with that and found that it was too slow, but it's possible it would be a reasonable change in the future.

**Comment by mrerrormessage** [comment]
I suppose @SethTisue 's comment brings up another question here - do we want to use Travis settings locally, or do we only want to use them only on Travis. Currently this branch is set up to have one setting used locally and on Travis. That could easily be changed. Thoughts @TheBizzle @qiemem ?

**Comment by SethTisue** [comment]
have any of us ever had these gratuitous failures locally?

**Comment by TheBizzle** [comment]
I've never experienced them locally.  I really think that the fixes for Travis should really only affect the Travis/CI builds.

**Comment by mrerrormessage** [comment]
The builds often take a very long time (hours) to run on my machine, and I've had some out of memory failures when running on a VM setup especially to try to simulate them, but I haven't had any of the sort that Travis has.

**Comment by TheBizzle** [comment]
Takes hours in your VM, or hours in your native OS?  My full builds usually take about 30 minutes.

**Comment by mrerrormessage** [comment]
Hours on my local machine. I'm retiming on a different branch to make sure it wasn't the settings in this branch slowing it down. The VM actually seemed to run them faster than my local machine.

**Comment by mrerrormessage** [comment]
@TheBizzle, I think this is ready for review. I've seen it pass Travis fairly consistently, and the changes are now Travis-only.

**Comment by SethTisue** [comment]
conceivably relevant: https://github.com/sbt/sbt/issues/1223

**Comment by mrerrormessage** [comment]
@SethTisue , I think it's worth keeping an eye on that issue. Given that we're on Java 8 and we restart sbt between compilation and test, it seems like we probably won't get the worst of it, but it may be relevant in the future if we continue to see killed builds.

**Pull request merged**
