### PR TITLE
Travis: cache dirs, for faster builds

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
@TheBizzle what are the failures here about, do you think?

**Comment by TheBizzle** [comment]
Just to get this on the record:

> java.lang.NullPointerException
	at scala.io.Source$.fromURL(Source.scala:141)
	at org.nlogo.tortoise.ModelDumpTests.resourceText(ModelDumpTests.scala:109)
	at org.nlogo.tortoise.ModelDumpTests.<init>(ModelDumpTests.scala:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:641)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] Could not run test org.nlogo.tortoise.ModelDumpTests: java.lang.NullPointerException

I've never seen that error before.  [This](https://github.com/scala/scala/blob/2.11.x/src/library/scala/io/Source.scala#L141) seems to be the line in the Scala standard library that is yielding the NPE, so `url` must be `null`.  The URL is obtained [here](https://github.com/NetLogo/Tortoise/blob/master/netlogo-web/src/test/scala/ModelDumpTests.scala#L109), where it's grabbed off of the classpath.

So this just brings us to the question "How can caching things cause us to not have our resources on the classpath?"  I don't currently know the answer to that question.

**Comment by TheBizzle** [comment]
Or is it possible that this caching is somehow changing the path of the resources or the path that we're using to ask for the resources...?

#MysteriesOfTheUniverse

**Comment by TheBizzle** [comment]
Closing due to inactivity.

**Pull request closed without merging**
