### PR TITLE
Add support for Fetch and Import-A extensions, and much more

### PR DESCRIPTION
**Pull request by TheBizzle**
Lord Jeremy, save me, I'm ready for this project to be over.

Here's my summary of what's in this PR:

  * Enable default arguments in NLW extensions
  * Add a macro for automatically generating the previously-hand-duplicated extension definitions file
  * Fix some bugs
  * Put polyfills into a dedicated `.js` file, instead of dumping them as janky Scala strings in `Compiler.scala`
  * Add support for `import-pcolors`/`import-pcolors-rgb`
  * Expose some stuff in the API (namely, the pure versions of `import-*` prims)
  * Use the latest version JVM NetLogo
  * Add infrastructure for docking tests to automatically install JVM NetLogo extensions
  * Add infrastructure for mandating that docking tests run with certain extensions that were not necessarily originally included in the model's "Code" tab
  * Have `export-world` and `import-world` deal with drawing data as base64
  * Add the Fetch and Import-A extensions
  * Test them
  * Update the dumps
  * Make the old `import-world` (and its ilk) throw runtime errors that suggest using Fetch and Import-A instead
  * Replace the uses of `import-world` in the testing infrastructur, and use the extensions now instead

### CODE REVIEW

**Comment by TheBizzle** [comment]
The "branch" tests failed, because (I think) the "pr-merge" tests and the "branch" ones interfered with one another during the import/export portion of `TestModels`.  I reran the "pr-merge" tests afterwards, and they passed, so we can consider all of the tests passed.

**Comment by LaCuneta** [comment]
This looks awesome!  I'm a big fan of pulling out the polyfill code into its own home, and of course of letting people get data in and out of their models in a sensible way.  I looked through the code and nothing caught my attention.

I pulled the branch down and tried to run it locally and hit a problem.  For the `Import-A` command tests:  `Fetch-Integration`, `ImportPcolors_2D`, `ImportPcolorsTopologyTest_2D`, and `RoundTripWithUTF8Chars` threw a `null` reference exception in `slurpByType()` because the `mimeType` was `null` from the call to `Files.probeContentType()`.  I did some brief checking and it looks like [`Files.probeContentType()` might not be reliable across platforms](https://dzone.com/articles/determining-file-types-java).  The other solutions listed there also don't seem great.  I tried letting `mimeType == null` through to be slurped as text, and that failed as well, probably because it wasn't really text.  I don't have a great solution, since the alternatives seem like a lot of effort for such a small thing that would only be used in development and testing. 

Other than that, I think this is good to go.

**Comment by TheBizzle** [comment]
:sob:

**Comment by TheBizzle** [comment]
Alright, I've just pushed a fix to the branch.  Everything should (hopefully) be in order now.  For maximum compatibility, uninstall your old version of the desktop edition of the Fetch extension.  (Deleting your `~/.netlogo` folder is a quick and easy way to do this.)

**Comment by LaCuneta** [comment]
I confirmed the change has things working on my machine now.  Waiting for the tests to pass and then I'll merge.

**Pull request merged**
