### PR TITLE
Wip javascript compiler

### PR DESCRIPTION
**Pull request by mrerrormessage**
Opening for review. Will depend upon https://github.com/NetLogo/NetLogo-Headless/pull/34. Won't build on travis until the bintray situation for parserJs is sorted out.

### CODE REVIEW

**Comment by mrerrormessage** [comment]
This should be ready for review. @qiemem , can you make sure that this gives you what you need? In particular, the response format is specified in `BrowserCompiler` and associated test.

**Comment by qiemem** [comment]
Will do. Probably won't be able to look till next week though.

**Comment by mrerrormessage** [comment]
The travis build is failing because it can't find the NetLogoHeadless artifact, but that artifact has been published [see here](http://dl.bintray.com/netlogo/NetLogoHeadless/org/nlogo/netlogoheadless/). Any ideas?

**Comment by TheBizzle** [comment]
I believe that your build needs this line: `https://github.com/NetLogo/Tortoise/blob/master/build.sbt#L37`.

Recall that using JCenter was causing problems, so we temporarily switched to hosting our artifacts in a repository that isn't clobbered by Typesafe Releases.

**Comment by mrerrormessage** [comment]
The test that is failing is due to [this commit](https://github.com/NetLogo/NetLogo-Headless/commit/de7258aad9d20cebdf684a38ad84917f041042f3) being pulled in with updated headless. Is there a fix expected for this in Tortoise soon?

**Comment by TheBizzle** [comment]
I believe that I already have a fix for this living in another branch.  I'll bring it over.

**Comment by TheBizzle** [comment]
If you rebase onto the current `master`, the fix for the test you mentioned should be available to you.

**Comment by mrerrormessage** [comment]
OK, I will have that done sometime tomorrow.

**Comment by TheBizzle** [comment]
I've been working on reviewing this, and I've noticed a lot of problems.  I find it particularly bothersome that there are two different objects that are `org.nlogo.tortoise.json.JsonLibrary`.  That's seems to me to be pretty not right.  These things that are living in different SBT projects should probably have different package names (e.g. `org.nlogo.tortoise.js`).

Also, numerous files are missing copyright notices (or point to the wrong repo with their copyright notices), there are unused imports and wildcard imports all over the place, and the style guide violations are innumerable.

I created a new branch (`wip-js-compiler-cleanup`) and implemented my share of the fixes over there.  @mrerrormessage, I'll take a look at this again once that branch has been cleaned up.

**Comment by mrerrormessage** [comment]
I'll pull over the changes. Is there a reason that you prefer to make code style changes yourself over asking me to do it? I've been waiting on the review of this PR for a while now. I've had time in which I could have made style changes which (presumably) would have hastened the code review for you.
As for JSONLibrary

**Comment by TheBizzle** [comment]
> The reason for the differing JsonLibrary files is that scala.js can't select at runtime which package to use because it doesn't support reflection, so the way to get around this is to provide alternate implementations at compile-time. We do this with several classes in NetLogo-Headless, where it didn't seem to be a problem. These classes include Femto, I18N, and Resource.

I still find it abhorrent and royally confusing, but *c'est la vie*.

> I didn't realize that for-comprehensions and class members should be aligned like val/var declarations

My interest is in clarifying relations between things, regardless of what language constructs are being used.

> When should type aliases be preferred over simply writing out the type?

For the same reasons that you would store a value in a local variable.  That is, to take something that is redundant or big and noisy, and give it a short, clear name.

> Should all traits be sealed until there is a reason not to?

Yes.

> Is it *ever* acceptable to write a function [application across multiple lines in Lisp style]?

I find that style incredibly annoying and hard to read.  I try to avoid it if at all possible.  Sometimes, I've found that I can't.  So it goes.

> I notice that you changed a lot of function calls [to declare the input variables on their own line]

It's not a huge deal to me, but I disagree with the Scala styleguide on this point.  When the parameters are not on their own line, I find it annoying, as if the functions are masquerading as blocks.  I don't read past a curly brace, and I doubt most other people do.  I find the extra line for parameters to be much clearer.  Also, declaring the parameters this way often extends the line too far.  I don't see what following the styleguide on this one buys people, except for ALL MIGHTY LINES OF CODE.

> Some imports you moved into a narrower scope and some you moved into a wider scope. How do you determine what the appropriate scope is for a given import?

These weren't a huge deal to me, and I'd need to know specifically what I moved that you're asking about, since I don't remember all of the imports that I moved/deleted/expanded/simplified.  I remember moving the import for the macro language feature into a narrow scope, because I hate language feature imports, and I didn't want it looking like a normal import.  I remember moving one import out of the top of a class, into the top level of the file because I didn't see what it was accomplishing in the narrower scope, being imported away from all of the related imports.

> There appear to be a number of files in the Tortoise project which have copyright notices pointing to NetLogo/NetLogo or are missing copyright notices altogether. Would you like me to fix all of the files on this PR or just the ones I edited (and do a separate PR onto master for the ones currently missing)?

The latter.

**Comment by SethTisue** [comment]
about "the differing JsonLibrary files”, this seems like it would be a great thing to put on a wiki page documenting the architecture, how and why the whole JVM/JS split works: in the code, in the build, etc.

**Comment by mrerrormessage** [comment]
Thanks for the comments @TheBizzle , they help me understand more about what style is expected in Tortoise/NetLogo-Headless.

That's a great idea @SethTisue. I'll see if I can whip one up this week to go along with merging this PR in with main.

**Comment by mrerrormessage** [comment]
@SethTisue , I have edited the [Architecture wiki page](https://github.com/NetLogo/Tortoise/wiki/Architecture#js-compilation) to add a section on Scala.js. I can move it to a separate page if desired, but it seemed to fit just fine with the rest of the Architecture page.

**Comment by SethTisue** [comment]
awesome!

I hadn't realized you had to write some little macros — that's pretty cool, too

**Comment by mrerrormessage** [comment]
I believe I've made the necessary style corrections. The build still isn't passing Travis, but I believe that's due to the flakiness of our build on Travis in general rather than the particular changes introduced here (there are no failures, just terminations due to I/O waits or OOM). I'll post again after the Travis changes have been merged in and (hopefully) made the build a bit more reliable.

**Comment by SethTisue** [comment]
> Should all traits be sealed until there is a reason not to?

normally I would seal a trait representing an algebraic data type, and not seal other traits

**Comment by TheBizzle** [comment]
Please do incorporate the `wip-scalajs-6` branch into this.

**Comment by mrerrormessage** [comment]
Sure thing! I'll comment again when that's complete.

**Comment by mrerrormessage** [comment]
This has been updated with the scalajs-6 changes. I suspect the tests will still fail due to Travis flakiness, but they may also pass because, hey sometimes we get lucky :four_leaf_clover: .

**Comment by TheBizzle** [comment]
I hate to keep dragging this on, and I really, really want to see this merged soon, but, now that our hopeful attempt at fixing Travis has been merged, mind rebasing this onto `master` and seeing if it passes the tests?

**Comment by mrerrormessage** [comment]
Will do.

**Comment by TheBizzle** [comment]
When merging this, I squashed down many of the commits, since they didn't compile.  The "individual, atomic commits" mantra is mostly valuable because it makes bisection and reversion much easier, but a commit that doesn't compile (or pass other simple forms of validation) merely makes that stuff harder, rather than easier.

**Comment by mrerrormessage** [comment]
Thanks!

**Pull request merged**
