### PR TITLE
`stop` should be able to propagate out to the interface

### PR DESCRIPTION
**Pull request by mrerrormessage**
`stop` creates a `StopInterrupt`, but it's captured by `Call` and unable to escape, so "forever" buttons' loops aren't terminated by the primitive call.

### CODE REVIEW

**Comment by mrerrormessage** [comment]
This allows Galapagos to detect when a button should `stop`, as well as allowing the language tests around `stop` and `report` to pass. Things that I have questions about or are otherwise uncertain of:

1) General approach: I'm using javascript exceptions to implement nonLocalExit. When a command is `stop`-ped early, it returns a `StopInterrupt`, which can be checked by anyone that cares (like a forever button) or ignored. I have this working to stop forever buttons on a local branch of Galapagos.
2) Performance: There seems to be a lot of FUD on the internet about the performance of javascript try/throw/catch. I think it would be possible to do an alternate implementation without try/throw/catch (both for `stop` and `report`) but I do not think it would be straightforward, either in the scala code generating it or in the resulting javascript. Note that the work on NetLogo-Headless allowed try/catch blocks to be generated only in blocks which actually use `_stop` or `_run`, which means that command procedures not using `_stop` should be unaffected. Reporters always use try/throw/catch, which could lead to performance problems, if the performance of try/throw/catch isn't up to snuff.
3) Plots: I wanted to make sure that the basic approach I was taking here was correct before I went through and changed a bunch of plotting code. I know at least `withTemporaryContext` and `withAuxRNG` will need modification to make this work.

**Comment by TheBizzle** [comment]
> General approach: I'm using javascript exceptions to implement non-local exit.

Obligatory, whining, on-the-record statement: I loathe using exceptions for control flow.

That said, I don't have a better, reasonable alternative to propose here.  If I did, I would have employed it to stamp out all of the exception-based control flow in this project.

I welcome any nicer alternative, but I'm not convinced that it exists, so let's just go with this.

> There seems to be a lot of FUD on the internet about the performance of javascript try/throw/catch.

Perhaps "FUD" is not the right term for this.  It seems [empirical](http://jsperf.com/try-catch-performance-overhead/39).  

That said, I'm generally not too concerned about the performance of our compiled code.  The real performance bottlenecks in NetLogo typically come from the engine.  Unless we have some evidence that this is actually problematic code, I think we should not reject it on the grounds of performance.

**Comment by SethTisue** [comment]
> I loathe using exceptions for control flow.

I suggest keeping your feelings about this in hand-written applications code separate from your feelings about it in code automatically generated by a compiler.

**Comment by mrerrormessage** [comment]
I'm pretty sure that stop/report can be implemented without exceptions, but it would involve doing control-flow analysis on the AST and may or may not mesh well with the existing structure of the Tortoise engine. There could be some other really nice stuff about doing CFA on the AST, it would *probably* make it easier for constructs like `loop [ every x ... ]` to be implemented in Tortoise, since you could figure out how to "pause" execution temporarily and check on UI updates. I'm going to run some benchmarks locally and make sure that this isn't going to slow Tortoise to a crawl, then we can have some actual numbers to discuss.

**Comment by mrerrormessage** [comment]
Running the BZ benchmark in V8 shows comparable performance between master and this branch. BZ isn't a great benchmark, since it doesn't really use stop or report. I'm trying to run Ants in nashorn or spidermonkey, but a comment in Benchmarker leads me to believe that that will be a futile endeavor. If this approach will suffice for now, I'll go ahead and start looking at the modifications needed for plots.

**Comment by TheBizzle** [comment]
:+1:

**Comment by mrerrormessage** [comment]
Engine code updated on a separate commit for easy review, but can be squashed as needed.

**Pull request merged**
